name: Gradle Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Make test directory
      run: mkdir test
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
#    - name: Enter test directory
#      run: cd test
#    - name: Move build libraries to jar file
#      run: mv ../build/libs/smoothie-web* ./smoothie-web.jar &&
#    - name: Java it!
#      run: java -jar smoothie-web.jar
