# YML Sucks
name: Smoothie-Web Jar Build Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Gradle
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    - uses: actions/upload-artifact@v1
      with:
       name: smoothie-web-spring-boot-jar
       path: build/libs
